version: '3.3'
services:
  web:
    restart: always

    image: dolphin-site-web
     
    build:
      context: .
      dockerfile: Dockerfile
    # command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    command: /usr/src/app/scripts/start_app.sh
    depends_on:
      - db
    volumes:
      -  .:/usr/src/app
    expose:
      - 8000
  db:
    image: mysql:8.0.26
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.envs/.prod/.mysql
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    volumes:
      - type: bind
        source: /srv/dolphin_test/mysql
        target: /var/lib/mysql

# Names our volume
  nginx:
    environment:
      - DOCKER_CLIENT_TIMEOUT=1200
      - COMPOSE_HTTP_TIMEOUT=1200
    build: ./nginx
    ports:
      - 1337:80
      - 443:443
    depends_on:
      - web

volumes:
  my-db:
