version: '3.3'
services:
  web:
    restart: always

    image: dolphin-site-web
     
    build:
      context: .
      dockerfile: Dockerfile
    # command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    command: /usr/src/app/scripts/start_app.sh
    depends_on:
      - db
    volumes:
      -  .:/usr/src/app
    ports:
      - 8000:8000
  db:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql_db
    environment:
      MYSQL_PORT: 3306  # cannot change this port to other number

      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # Opens port 3306 on the container
      - 3306:3306
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

# # Names our volume
#   nginx:
#     environment:
#       - DOCKER_CLIENT_TIMEOUT=1200
#       - COMPOSE_HTTP_TIMEOUT=1200
#     build: ./nginx
#     ports:
#       - 80:80
#       - 443:443
#     depends_on:
#       - web
