# Generated by Django 3.1.4 on 2023-01-28 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_pregunta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributo_delfin',
            options={'verbose_name': 'atributo de delfin', 'verbose_name_plural': 'atributo de delfines'},
        ),
        migrations.AlterModelOptions(
            name='delfin',
            options={'verbose_name': 'delfin', 'verbose_name_plural': 'delfines'},
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='valor',
        ),
    ]
