# Generated by Django 3.1.4 on 2023-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20230128_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='positivo',
            field=models.BooleanField(default=True),
        ),
    ]
