# Generated by Django 3.1.4 on 2023-01-28 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_pregunta_positivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atributo_delfin',
            options={'ordering': ['atributo'], 'verbose_name': 'atributo de delfin', 'verbose_name_plural': 'atributo de delfines'},
        ),
        migrations.AlterField(
            model_name='atributo_delfin',
            name='valor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
